# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_1_xdc.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_andgate_0_0/design_1_andgate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_andgate_0_0 || ORIG_REF_NAME==design_1_andgate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_notgate_0_0/design_1_notgate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_notgate_0_0 || ORIG_REF_NAME==design_1_notgate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_notgate_1_0/design_1_notgate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_notgate_1_0 || ORIG_REF_NAME==design_1_notgate_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_orgate_0_0/design_1_orgate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_orgate_0_0 || ORIG_REF_NAME==design_1_orgate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_andgate_1_0/design_1_andgate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_andgate_1_0 || ORIG_REF_NAME==design_1_andgate_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_orgate_1_0/design_1_orgate_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_orgate_1_0 || ORIG_REF_NAME==design_1_orgate_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_orgate_2_0/design_1_orgate_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_orgate_2_0 || ORIG_REF_NAME==design_1_orgate_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_andgate_1_1/design_1_andgate_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_andgate_1_1 || ORIG_REF_NAME==design_1_andgate_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_andgate_0_1/design_1_andgate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_andgate_0_1 || ORIG_REF_NAME==design_1_andgate_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_andgate_0_2/design_1_andgate_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_andgate_0_2 || ORIG_REF_NAME==design_1_andgate_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_andgate_0_3/design_1_andgate_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_andgate_0_3 || ORIG_REF_NAME==design_1_andgate_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_andgate_2_0/design_1_andgate_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_andgate_2_0 || ORIG_REF_NAME==design_1_andgate_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_andgate_2_1/design_1_andgate_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_andgate_2_1 || ORIG_REF_NAME==design_1_andgate_2_1} -quiet] -quiet

# XDC: c:/Users/thatcher/Desktop/Project3-1/Project3-1.gen/sources_1/bd/design_1/design_1_ooc.xdc
