set_property IOSTANDARD LVCMOS33 [get_ports {e[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports S1]
set_property IOSTANDARD LVCMOS33 [get_ports S2]
set_property PACKAGE_PIN U16 [get_ports {e[0]}]
set_property PACKAGE_PIN R2 [get_ports a]
set_property PACKAGE_PIN T1 [get_ports b]
set_property PACKAGE_PIN U1 [get_ports c]
set_property PACKAGE_PIN W2 [get_ports d]
set_property PACKAGE_PIN T2 [get_ports S1]

set_property PACKAGE_PIN R3 [get_ports S2]
